### ISSUE TITLE
Push the remainder of the code base to GitHub

### ISSUE THREAD

**Issue by AndruC** [HumanityInc/Humanity#5] opened 2015-03-02 17:47 UTC
I am, at Masha's request, posting this here.

Please push the remainder of Humanity's codebase to GitHub so that other contributors can get a better understanding of the ecosystem in place.

Both Max and Masha have acknowledged that a large part of the codebase is still private, but there is no need for that if it is pushed to development or feature branches. Keep the master branch the way it is, but put the rest up.

**Comment by AndruC** [comment] 2015-03-02 19:37
It is the development of new features, not the polishing of existing ones, that will bring new contributors to Human. Give your CTO, profess0r-x, a break!

**Comment by stephen-cornwell** [comment] 2015-03-05 02:44
I second this. Only a fraction of the features described as complete or almost complete seem to be have been submitted.

**Comment by HumanBe1ng** [comment] 2015-03-05 03:00
Yes yes, as I have already mentioned, in the immediate future this git will be updated daily. :) I'm afraid it's missing a whole lot of things, and some of what it does have is outdated.. This is because engineering is focusing on getting the beta out as soon as possible, and not pushing and commenting code. We will catch up though - once the beta is fully launched in the next 48 hours or so, we will upload 100% of everything we have finished here. And we will begin the process of commenting the code so that you guys can figure out what's what without having to spend a ton of time on it. :) 

We also have really cool side projects that we are going to pitch to the open source community to see if anybody wants to build, but we will build them ourselves if we have to - it's really cool stuff. :) They're all part of our network, just little apps and such. Green activation emails are going out to all of the top 101, my best guess, the day after tomorrow. We are 97% ready now according to Alex. I just checked out the latest build and yea, it's almost almost ready. Just a few more features to put in and a few very small visual tweaks (opacity of certain items, that sorta thing) and it'll be ready to go! :)

P.S. Andrew, we have to polish the existing features because everything we release is "PERFECT." It has to be. Our company, our very lives depend on this. If we release unfinished crap, that's no way to do business.. Far better to take the extra time to polish up your amazing product. Look at every game developer who has ever succeeded or failed to see how 100% true this is in real world terms. Quality is everything. Deadlines no one gives a damn about. Do you remember Half-Life for being GREAT, or do you remember when the beta was released? Exactly.. :)

**Comment by stephen-cornwell** [comment] 2015-03-05 03:07
Well written code needs very little commenting. And well managed development should result in small, regular check ins. Pushing code to Git takes seconds when there's only one contributor and not much more when there are several.

Also, where's the database schema?

**Comment by HumanBe1ng** [comment] 2015-03-05 03:36
Tomasz from Poland asked for comments, so we will add comments. :) We wanna make this as well as possible for you guys.. Remember, all of this code is "alive," in the sense that it is being improved daily, and it will CONTINUE being improved daily for as long as time exists.. This is a never-ending process, kind of like building google.com or facebook.com is a never-ending process.. :) What is your honest opinion of the code so far? It looks great to me, but my knowledge of programming is mostly limited to HTML and CSS. We are going to post links to this git on 10+ open source communities soon, including golang-nuts and so on. So there will be a LOT of feedback. What is your honest opinion so far (honest meaning not kind for the sake of being kind or mean for the sake of being mean - just facts)? :)

**Comment by AndruC** [comment] 2015-03-05 04:12
Can we have profess0r-x chime in on this topic?

**Comment by rjamesnw** [comment] 2015-03-05 04:29
Even well written code needs commenting.  Sometimes it's easier to know what was in the mind of the developer when they did a certain thing.  When code gets very large, it's easy to forget why something was done some way 8 months ago, so trust me, it's better now, as I doubt any developer will keep a mental note of where comments should be later.

**Comment by AndruC** [comment] 2015-03-05 04:32
> Also, where's the database schema?

**Comment by rjamesnw** [comment] 2015-03-05 04:36
No idea. :/

**Comment by stephen-cornwell** [comment] 2015-03-05 06:18
> Even well written code needs commenting. 

Agreed to a degree, but well written code means concise methods with a single purpose which should be clear from the declaration. If you follow SOLID principles commenting shouldn't be necessary except for APIs and decisions which aren't clear from the code. Lots of comments inside a method is usually a sign your methods are too complex, code is poorly written or your naming is confusing. But this probably isn't the place for a debate on the merits of commenting :)

The code as it is can be checked in without comments, it only takes a moment and won't affect the developer's ability to add them going forward. But I guess we'll see when it's all checked in in the next couple of days. It would be good to see the schema before then though so we can more easily set up a working build.

**Comment by rjamesnw** [comment] 2015-03-05 15:37
I understand your point, but the SOLID principle only means you end up with a lot more concise methods and classes, which in whole (and even still, internally) won't make much sense as a whole.  You go from a 50 piece puzzle set to 1000, and without good commenting, or even docs at this point, nothin makes sense (as a whole).  I've been developing with Google V8, for example, and it seems to be very SOLID in most parts, much that doesn't make understanding how those parts fit any easier - mostly because the commenting in code is too sparse. It's like finding the head of a flower on that 1000 price puzzle, and thinking "for sure, it's near the bottom", lol. (assuming there isn't a flower pot somewhere higher in the picture ;) )

**Comment by stephen-cornwell** [comment] 2015-03-05 20:53
There's a spectrum and I suspect my idea of very little commenting is probably closer to your idea of adequate commenting than you think. I'd rather developers focus on making their code readable and understandable than explaining away every decision. But there are no hard and fast rules in programming though, as I'm sure you're aware. I hate jigsaw puzzles, but I like the analogy!

**Comment by rjamesnw** [comment] 2015-03-05 21:10
;)

**Comment by Jarema** [comment] 2015-03-10 10:46
In my humble opinion, there is no such thing, as good code without comments. Comments are big part of the quality of the code. It's not only performance, stability and concise. It's about readibility too. Programmers most of the time spend on reading the code, not writing it, and being able to read it fast and with full understanding is crucial.  Look at good codebase examples - like golang standard library. I so NO SINGLE benefit in lack of comments. It doesnt impact performance, and if You already understand it well, You just skip them. Plus, in golang, which is the case, comments are docummentation.

Reading code with  good comments is a pleasure. It's like a well written book or a journey. You can understand it parts, and it's concept as a whole. Of course You can understand it without them, but with how much bigger effort? How much time it will take? Why?

My coworker asked me why my code in company is so often reused. Probably becuse it was easy to use. Because of extensive comments. Noone had to ask what is doing what, or dig the code for hours. It was there.

Thats my few words on that case :).

PS Stephen - I would be happy if You show me some metodologies and studies about not commenting the code and why. I'm always willing to learn new things :).

**Comment by stephen-cornwell** [comment] 2015-03-10 20:54
Jarema, you're arguing a point I didn't make. I did not claim good code requires **no** commenting, I said _minimal_. If you use sensible, verbose naming and follow SOLID principles your code should be, for the most part, self evident. Commenting self evident code is pointless, increases code maintenance and consumes time better spent on something productive. Where code cannot be self evident or the decision to implement something in a certain way is non obvious then commenting is essential.

I would strongly argue against "extensive comments" in _most_ cases. If your code requires extensive comments to be understood I would suggest it needs refactoring and you've failed to keep your code SOLID. If your code doesn't require extensive comments but you're writing them anyway you're just wasting your time, your employer's money and creating a maintenance overhead.

To be clear, I'm talking about commenting code, not documenting public methods or APIs. That's an entirely different story. And as I said previously, this isn't a hard and fast rule. Different problem areas, with differing levels of complexity, require different levels of commenting. But as a general guideline I aim to make my code clear enough that commenting is redundant and comment only when that cannot be achieved. Comments shouldn't be used as a crutch for unclear code.

**Comment by stephen-cornwell** [comment] 2015-03-16 11:06
Max, what happened to this?

> Yes yes, as I have already mentioned, in the immediate future this git will be updated daily. :) 

And this:

> once the beta is fully launched in the next 48 hours or so, we will upload 100% of everything we have finished here.

**Comment by Jarema** [comment] 2015-03-18 12:39
Stephen, I disagree in many points You've made, but i feel this is not the place for such discussion :).

There are much bigger problems here right now:
- silence from Max and no word from maintainer. again unfullfiled promises and deadlines.
- code quality: we can discuss  about lot of comments or minimal, but now there are none, plus no readme file. ergo: i doubt anywone want to step in that code and contribute.

**Comment by stephen-cornwell** [comment] 2015-03-20 10:25
Jarema, I'm happy to agree to disagree and focus on the relevant issues.

Interesting that the maintainer hasn't spoken up at all. And I'd agree the code isn't in a state that anyone would want to contribute. This project is a bit of a non starter at this point.

**Comment by HumanBe1ng** [comment] 2015-03-20 10:36
Guys sorry I have no time to read this - I don't even have time for media and investors. I'll read next week. With deadlines, I go by what Alex tells me - he's the dev, so if he says 2 days I say 2 days. He ran into a bunch of issues with Angular at the end (not surprising knowing Angular), and he's doing the best he can. He wants to upload everything once he's finished. He again tells me now that it's ready, but you know what let me take the latest build for a spin guys and then I'll tell you myself.. :) Keep an eye on HumanityTexhnologies.com - all the news is there.

**Comment by Jarema** [comment] 2015-03-20 10:47
What kind of issues? Maybe we can help.  Honestly, I had "bunch of angualr issues" only with my first angular project. after that - You know what to do and how. In case of problems with huge dynamic lists, there is always a possibility to create directives affected by that problem using ReactJS. Any other issues - just ask.

**Comment by HumanBe1ng** [comment] 2015-03-20 11:21
Thanks I think it's all good now - with Angular he just has to work out a stupid bug with the custom scrollbar. Should be done with that and other small stuff today. He was already asking yesterday if we should let the rest of the top 101 in (only 4 are in right now) but I was like woah woah let's try the final thing first and add some decent content.. :)

**Comment by HumanBe1ng** [comment] 2015-03-20 11:25
Honestly I'm so ridiculously busy that even if he takes another 2 weeks that is perfectly fine with me - I'll be caught up by then. :D But he says he is doing it today.. We'll see.. In any case I wanna add some small stuff after we launch the latest beta, and more content too.. Don't expect it until some point next week (and not first thing either). :) Honestly screw deadlines, after this experience we are adopting id Software's world famous "When it's done" motto. Deadlines just ruin everything, or at least they WOULD if I ever paid any attention to them.. :) Seriously, you gotta focus on the QUALITY of what you are making, NOT on how quickly you can ship it to fill your pockets up with money.

**Comment by stephen-cornwell** [comment] 2015-03-22 22:33
There are some pretty big differences between what you're doing and what id software did. First, they never said they were launching until they were actually launching. Second, they weren't an open source project. Though at this stage neither are you really.

**Comment by lamarrotems** [comment] 2015-03-24 17:02
Max, any updates?

**Comment by HumanBe1ng** [comment] 2015-03-24 23:58
Guys I'm very sorry I'm extremely busy and have a 1 week long+ back log of items on my to-do list. Once we finish the beta in the days ahead (hah, how many times have I said this), Alex and I will sit down and read every single post here and respond to absolutely everything. If there are any ideas here that we should incorporate, we will incorporate them. I received today from Alex a list of the 7 final items that need to be done - it's all really tiny cosmetic stuff, for example the change password box doesn't fit into one of the menus because it already has too much other items. Very very small stuff, most of which literally takes minutes to fix. I was up working all night so I just woke up - I will post a photo of that list here later, along with translations (Alex speaks English, but it's faster for him to write in Ukrainian or Russian). See you guys in a few hours I'm gonna go have this same exact meal in this same exact place.. :)

https://instagram.com/p/yrhbIdGMKu/

**Comment by HumanBe1ng** [comment] 2015-03-25 00:00
By the way we currently have fifty (50) projects on the go, of which Touch and Empower are just two. Insane, I know. I will make a nice infographic in the form of a wheel when I return from breakfast. :) All of these projects are progressing at the same time - four of them are mobile apps, about which by the way there will be a big update posted in the days ahead. I will also post more info about the apps here when I return tonight. Cheers!

**Comment by lamarrotems** [comment] 2015-03-25 02:02
You have just said that so many times it is getting hard for us all to
believe. :( We are excited for the social network but that interest will
not hold forever.

**Comment by stephen-cornwell** [comment] 2015-03-25 06:56
Perhaps if you focus on one project of the 50 at a time you might actually get one finished.

All your posts are the same: I'm very busy, it's almost done. But there doesn't seem to be any progress.

Again, what happened to this:

> Yes yes, as I have already mentioned, in the immediate future this git will be updated daily. :)

And this: 

> once the beta is fully launched in the next 48 hours or so, we will upload 100% of everything we have finished here.

That was three weeks ago.

**Comment by Jarema** [comment] 2015-03-25 07:03
Max, with all the kindness, this is github. Here nobody cares how busy You are, how great the project is and even what You want to do with it. Github is only about code and cotribution. Topics like this are making humanity issues messy and fuzzy. We should focus on code, and discuss all non-code related stuff elsewhere. Plus, I understand that Alex prefer to write in russian/ukrainian, but repo with silent maintainer is a dead repo, sooner or later, and here it's very rare to write longer posts then 2 sentences, so it should not be a problem. Another thing - You again gave us an ETA for some update, and missed it. Ok, dont give any deadlines, but when You do, care about them more.

**Comment by HumanBe1ng** [comment] 2015-03-25 12:11
Tomasz (Jarema) you are starting to get on my nerves - you asked why I wasn't responding, so I explained that I'm busy. I don't need to hear a damn speech about how "nobody cares how busy I am." Say THANK YOU that I took my time away from building a BILLION dollar company for YOU, and don't complain. Like seriously, I have put in almost 4 years, 10,000+ hours, and literally every CENT of my money - learn to show a little gratitude. I generate 2 million USD worth of value for the company (2.5 billion divided by 3.5 years) per DAY - money that would have been MINE had I not chosen to give it to YOU. And you, having invested all of 5 github comments and 3 emails, are now reading me lectures. You do understand that I work 12 hours a day average, 7 days a week, that means each HOUR I work I generate $166,000 for this company, FOR mankind. That means that if I have to take TEN MINUTES to read something you wrote and respond to it, like I am doing now, that is almost 28 THOUSAND DOLLARS lost to the company, and to all of humanity. That could have bought meals for 100,000 people. So PLEASE, only comment if you have something EXTREMELY IMPORTANT to say - definitely NOT to complain that I took the time to respond to your earlier inquiry! You have to understand that this company, or ANYBODY here, owes you NOTHING - you have done (almost) nothing for us, while we have given you (literally) EVERYTHING we have. Yes we are late. Get over it. :)

**Comment by HumanBe1ng** [comment] 2015-03-25 12:13
Again, to respond for the THIRD (or fourth?) time about deadlines and Alex: yes, to hell with deadlines, I have ZERO respect for them - I focus on QUALITY, NOT timing. ALWAYS. As I said, from now on our motto is "when it's done." Whenever we announce release dates, we will announce them as TENTATIVE, and we will make sure it is PUBLICLY KNOWN that we focus on QUALITY above TIMING. With respect to Alex, AGAIN, as I have said already TWICE, once we launch, he will be here ALL the time, will update DAILY, will respond to comments. Now would you like me to repeat myself a FOURTH time, or may I get back to work now please and thank you I've been up all night. :)

**Comment by HumanBe1ng** [comment] 2015-03-25 12:24
Stephen, the EXACT same thing, WORD FOR WORD, applies to you man. I have already addressed the subject of deadlines FIVE times - there is no need to ask me for the SIXTH time why we are late. You are WASTING my time. No, we will work on as many projects as we like, thank you very much - I think that after 16 years and 6 companies I KINDA have a LITTLE bit of an idea what I'm doing. The way business is currently approached worldwide is WRONG - companies focus on VERTICAL growth of a single product or two, whereas we are taking the CORRECT approach - HORIZONTAL growth first (many projects started), then exponential growth of ALL of them combined, with ONE FUELING THE OTHER. This results in overall growth that is something like 1000%+ what businesses normally expect. We know what we're doing. And you also have to understand that there isn't "little progress" - there is an INSANE amount of progress, SO MUCH progress that I could sit here FOR TEN HOURS (literally) just writing a short novel here for you about our progress in JUST THE LAST SIX MONTHS, of which you, because you are NOT seeing what goes on INSIDE the company, are only seeing something like 0.01%. You have to understand that just because YOU don't see it, doesn't mean it isn't THERE. This git is for TWO projects out of FIFTY, and it hasn't been updated in 25 days - what do you think we have been DOING these 25 days - do you think we've been SLEEPING? No, work goes on here SEVEN DAYS A WEEK TWENTY FOUR HOURS A DAY. At ANY point of ANY day, somebody SOMEWHERE is doing SOMETHING. 24/7/365. No holidays. No birthday. No New Year's. No Christmas. All for a company which we are GIVING AWAY TO YOU PEOPLE. So please, again, learn to say THANK YOU, and act accordingly. We DO appreciate your input, but not your WHINING - input must be CONSTRUCTIVE, it must consist of USEFUL ideas that BENEFIT the company, not a fifth in a row "Why are you late?" question. THANK YOU VERY MUCH, PLEASE BE PATIENT! ALEX HAS TO SLEEP he cannot work 24 hours a day HE IS DOING THE BEST HE CAN! There is a TON of new devs joining VERY shortly there will be a BIG update about the apps and a TON of other stuff later this week! BE PATIENT we've been working on this for FOUR YEARS - creating WORLD changing technology IS NOT A QUICK PROCESS! :) Gracias, see you in a few days when we finally let the rest of the top 101 in (only 4 are in so far), update the git, when Alex and I sit down and go through all of your technical suggestions above. Thanks again and I hope I'm not being harsh - you have to understand that despite my chronic overuse of smiley faces I take this EXTREMELY seriously and am VERY VERY busy - when somebody takes my time away from the work of my life to do ANYTHING but help the work of my life, it understandably makes me VERY upset - there is NO point to my life other than this company. None. Zero. This is everything - this is the reason I'm alive.

**Comment by HumanBe1ng** [comment] 2015-03-25 12:25
Damn, you gotta be impressed by how much I can write in 12 minutes (the last 3 posts). :)

**Comment by Jarema** [comment] 2015-03-25 13:59
Damn, that was most arrogant post I've seen in a loooong time. You're time isn't more valuable at all than anyone's else. And it will never be. No matter who You will become - a beggar or a bilionaire (isn't that what ishuman.me is about, ironically?).

 I was here only for code, not Your ideas.

I was, because You dont respect people You want to work with, and I dont respect people who don't respect others, and I just decided to cease any further assistance or cooperation. I prefer to give my time to others.

Providing deadlines (You did, few days ago) and not caring about them is disrespectful towards people, at whom they were adressed.

And please, don't say, that You gave me anything. You didn't. And I never wanted anything, beside writing good code. I do not need money.

Goodbye.
I wish You best, really, but with that attitude, it might be "quite" hard.

PS Learn some humility, please.

**Comment by HumanBe1ng** [comment] 2015-03-25 14:04
And AGAIN you waste my time just to feed your ego. If you think that your time is as valuable as mine, provide proof that you deliver $166,000 USD / hour in value to the global community or more. Because right now you deliver zero dollars - you work for yourself and yourself only, while I give EVERYTHING I make to others. And you're here to teach ME about humility? And RESPECT? That is the funniest thing I've ever HEARD! What assistance and cooperation are you talking about? How have you assisted us? By wasting my time? And now you're gonna run away because you didn't like a taste of reality? DON'T LET THE DOOR HIT YOU ON THE WAY OUT BUDDY!! :)

**Comment by mashahuman** [comment] 2015-03-25 14:25
Hi! Hey, folks, any of your previous experience is not applicable to Humanity and Max, because no companies even closely did what he does. How personally I get GREAT joy from cooperation with Max: I simply listen to what exactly he says, then do what I want, but only in terms of his recommendations, and thus I am NEVER disappointed, but am always happy to be there and always have something to do. I don't think that any further dialogues now will have any sense, but I will be happy to read all the correspondence when Max and our backend programmer come here when they do. :) See you! I wish you all to have a very nice day! / If you want to, come to my fb (/masha.human) tomorrow to see my thoughts about why exactly Humanity's structure and strategy are oh-so-naturally-correct, beautiful and unbeatable! :) (I am sorry, I wanted to make a really short comment, but I am indeed glad to be here, sorry :) ).

**Comment by HumanBe1ng** [comment] 2015-03-25 14:27
My mind BOGGLES at the WILD INSANITY of a comment such as "the time of a beggar and billionaire is equally valuable." I'm sorry, I just had to add this. So like, the time of BILL GATES, who has saved MILLIONS OF LIVES, is as valuable as that of a homeless guy who sleeps in the park? Oh dear god, the lies people tell just to feed their ego are STARTLING.

**Comment by mashahuman** [comment] 2015-03-25 14:30
Is there such a saying? Wow!
This is one of the biggest mistakes a person can make. Because this makes you a pure robber
Why?
Watch my video on fb these days

**Comment by Jarema** [comment] 2015-03-25 14:51
No, there is no such saying.

It's just me - to value kind beggar time higher, then rude and
disrespectful bilionaire's time.
And please, leave Your worldview to Yourself. I'm was not here to talk
about ethics. If I did, I would probably talk about Rousseau, Mill or
Spinoza, not about one's youtube video's.

Bye, and have a lot of smiles,
Tomasz

2015-03-25 15:30 GMT+01:00 Masha Human notifications@github.com:

**Comment by HumanBe1ng** [comment] 2015-03-25 14:56
Dude, YOU are the one being rude and disrespectful here! Look at the CONTEXT of this situation (me giving away BILLIONS; you giving away WHINING), then look at YOUR OWN RUDE ATTACK COMMENTS ABOVE, AND WAKE THE HELL UP! The fact is that you are just JEALOUS, and to pour water on your flaming EGO you are willing to make up a loooooootttt of lies as is perfectly illustrated above. NOW GO AWAY AND STOP WASTING MY DAMN TIME! Thank you very much for your "cooperation" byee byee!! :)

**Comment by Jarema** [comment] 2015-03-25 15:11
Speaking about something doesn't make it true. Noone saw those billions yet, but thats ok.
Everyone will be happy if they will. Including me. Just  because I dont agree with You doesnt mean I don't wish You best. You could learn from it. Bye.

**Comment by HumanBe1ng** [comment] 2015-03-25 15:16
It's not "speaking," it's 4 years of work and 2,500 million US dollars to show for it - "speaking" is what YOU do.

Also, given the BARRAGE of fabricated personal attacks above, coming back now to say that "you wish me the best" is LAUGHABLE. If you wished ME, or the human SPECIES the best, you wouldn't do anything other than SUPPORT a company that has dedicated her LIFE to helping that species, and the man who did the same.

So perhaps YOU could learn from it.

Bye (hopefully for real this time - please!).

**Comment by lamarrotems** [comment] 2015-03-25 15:17
Max, there is no billions. Please face it. Your proof for the billions were
these products which were never released. Until they are released you have
a company worth $0.

**Comment by Jarema** [comment] 2015-03-25 15:18
Show us those millions. It's that simple.

**Comment by HumanBe1ng** [comment] 2015-03-25 15:22
We have had 4-5 offers so far over the past 12 months to invest at a billion dollar valuation.

The latest few were at a 2.5 billion dollar valuation.

Stop making up lies to quiet your raging jealousy.

Also, do you want me to show you the definition of STUPID?

Here:

"Stupid: speaking out AGAINST the value of your own company."

Tomasz if you come back here again I am going to ask github to ban you from our git since you obviously can't help yourself.

**Comment by mashahuman** [comment] 2015-03-25 15:23
Jarema, I have only followed your manner of wise conversations. My mistake
It is SO NICE to hear that you wish us the best! This puts us onto the same line!
But what you say about billions is telling to a pregnant woman "I will never believe you that you'll have a baby despite of your belly". Do you understand such allegory? :)
I don't know what exactly should be the lesson for Max here, but: MAAAX, WE REALLY HAVE A LOT OF WORK RIGHT NOW INSTEAD OF THESE CONVERSATIONS! :) Max, I completely support you in everything and have nothing to add even. But really, we have just wasted a lot of time collectively! Guys, respect his time (which is exactly billion times more precious than a beggar's time. if not - why are you now talking to him, not beggars now? :)) and respect yours! :)

**Comment by mashahuman** [comment] 2015-03-25 15:24
And what Max said above is completely true: we have had those offers
And the bad thing is that you know this PRECISELY
And this is a very, extremely bad sign of.. am I sorry to say this, but a FAT LIAR

**Comment by lamarrotems** [comment] 2015-03-25 15:26
Those offers are not real, and we all know it.

Anyone can say that they have billions dollars offers...

**Comment by HumanBe1ng** [comment] 2015-03-25 15:26
Oh god you are a moron..

**Comment by mashahuman** [comment] 2015-03-25 15:27
I would understand everything if you were just asking questions
But you keep telling lies over and over again pretending that will make them true
But this only humiliates you, people. Why do you even do this to yourselves? :)
Truly. :) 
Max has given you so many chases to keep dignity
Why do you humiliate yourselves? I believe that you are great guys inside and this is just a misunderstanding..somehow..I don't know how, because everything is clear..but I still believe in the best of you.

**Comment by HumanBe1ng** [comment] 2015-03-25 15:28
It's DISGUSTING that this is the kind of shit I have to deal with.

Jealous losers FABRICATING LIES to quiet their pathetic jealous little egos.

You guys are SAD.

GROW UP.

**Comment by mashahuman** [comment] 2015-03-25 15:28
Ahahahaha
RIGHT NOW RIGHT HERE!!!!
HOW EXACTLY CAN YOU KNOW THAT OFFERS ARE NOT REAL???
RIGHT HERE RIGHT NOW ANSWER, OTHERWISE YOU ARE...I HAVE NO WORDS :)

**Comment by mashahuman** [comment] 2015-03-25 15:29
Because the only two people here who CAN know that they are real both say that they are.
:)

**Closed as completed by HumanBe1ng** 2015-03-25 15:28 UTC

**Comment by HumanBe1ng** [comment] 2015-03-25 15:31
I am closing this issue since this is a complete goddamn waste of everybody's time.

This git will be updated as quickly as possible once the beta is launched in the coming days, hence the issue is settled.

Updates will continue daily or every several days from that point forward.

Have a nice day everybody - I sure as hell will! :)

**Comment by lamarrotems** [comment] 2015-03-26 09:19
Hey guys I just got a hundred million dollar offer from Tom from Myspace, but I can't disclose what it's for quite yet. Will post tomorrow. But it's going to majorly helped Humanity Incs source code. Spent 16 hours a day for past 12 years working on this idea, so it's good. And I'm going to donate half the money to Humanity and the other half to charity. Have to go to sleep now, meeting with Bill Gates tomorrow. Will post proof of everything in next day or two. But it's huge....
